version: '3.8'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}
    tenderduty_data: {}

services:

######################################################################################
#####################         TRAEFIK PROXY CONTAINER          #######################
######################################################################################      
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    expose:
      - "8082"
    ports:
      - "443:443"
      - "80:80"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic_config.yml"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=$EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/config/dynamic_config.yml:/dynamic_config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - monitor-net
    labels:
      - "traefik.enable=true"

######################################################################################
#####################           GRAFANA CONTAINER              #######################
######################################################################################
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=true
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.rule=Host(`$GRAFANA_HOST`)"


######################################################################################
#####################          PROMETHEUS CONTAINER            #######################
######################################################################################
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net

######################################################################################
#####################         NODE EXPORTER CONTAINER          #######################
######################################################################################
  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net

######################################################################################
#####################             CADVISOR CONTAINER           #######################
######################################################################################
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net

######################################################################################
#####################                TENDERDUTY                #######################
######################################################################################
  tenderduty:
    image: ghcr.io/blockpane/tenderduty:v2.2.1
    container_name: tenderduty
    volumes: 
      - tenderduty_data:/var/lib/tenderduty
      - ./tenderduty/config.yml:/var/lib/tenderduty/config.yml
      - ./tenderduty/chains.d:/var/lib/tenderduty/chains.d
    restart: unless-stopped
    expose:
      - 8888
      - 28686
    networks:
      - monitor-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tenderduty.loadbalancer.server.port=8888"
      - "traefik.http.routers.tenderduty.entrypoints=websecure"
      - "traefik.http.routers.tenderduty.tls.certresolver=myresolver"
      - "traefik.http.routers.tenderduty.rule=Host(`$TENDERDUTY_HOST`)"

######################################################################################
#####################                GOVSTAT                   #######################
######################################################################################
  govstat:
    image: kw1k/govstat:v2
    container_name: govstat
    volumes:
      - ./govstat/chains.yml:/govstat/chains.yml
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK}
      - SLEEP_TIME=43200 #IN SECONDS
    restart: unless-stopped
    networks:
      - monitor-net